cargo run --release --\
    --decay 0.05\
    --n-particles 4000\
    --turn-speed 1.8\
    --dt 0.5\
    --move-speed 0.1\
    --sensor-spread 0.8\
    --sample-dist 3.0\
    --deposit-rate 1.0\
    --diffusion 0.01\
    --steps-per-frame 5\
    --record out.slm
